using System.Diagnostics;
using Microsoft.VisualBasic.FileIO;
using Microsoft.Web.WebView2.Core;
using PDFLight.Classes;
using PDFLight.Controls;

namespace PDFLight.Forms;

public partial class MainForm : Form
{
    private readonly AppSettings settings;
    private readonly PdfViewHost viewHost;
    private readonly string startFile;
    private readonly Dictionary<string, Image> programIcons = new(StringComparer.OrdinalIgnoreCase);
    private FileInfo currentFile;
    private int currentPageCount = -1;      // -1 = nicht bestimmbar (z.B. verschlüsselt)
    private DateTime loadedWriteTimeUtc;    // erkennt externe Änderungen an der angezeigten Datei
    private string undoBackupFile;          // Sicherungskopie für einstufiges Rückgängig
    private string undoTargetFile;          // Datei, für die die Sicherung gilt
    private bool isFullScreen;              // F11-Vollbild (randlos, ohne Tool-/Statusleiste)
    private FormWindowState fullScreenPreviousState;

    public MainForm(string startFile)
    {
        InitializeComponent();
        try { Icon = Icon.ExtractAssociatedIcon(Application.ExecutablePath); } // Fenstersymbol = Programmicon der EXE
        catch (Exception ex) when (ex is ArgumentException or IOException) { }
        this.startFile = startFile;
        settings = AppSettings.Load();
        Lng.Initialize(settings.Language); // vor PdfViewHost (Viewer-Sprache) und vor allen Dialogen
        Lng.Apply(this);
        // Mehrzeilige Tooltips brauchen explizite Schlüssel (Zeilenumbrüche taugen nicht als resx-Schlüssel)
        btnOpen.ToolTipText = Lng.T("Tooltip.Open", btnOpen.ToolTipText);
        splitButtonMove.ToolTipText = Lng.T("Tooltip.Move", splitButtonMove.ToolTipText);
        ddbEdit.ToolTipText = Lng.T("Tooltip.Edit", ddbEdit.ToolTipText);
        statusIndex.ToolTipText = Lng.T("Tooltip.StatusIndex", statusIndex.ToolTipText);
        viewHost = new PdfViewHost(webView);
        // Eigene (nicht auto-generierte) Menüs zuweisen: Auto-Menüs übernehmen in WinForms die
        // Symbolgröße der Symbolleiste live (IsAutoGenerated delegiert den Getter) — eigene Menüs
        // behalten dagegen fest 16-px-Symbole und die Standardschrift, egal wie die Toolbar eingestellt ist
        foreach (var item in new ToolStripDropDownItem[] { btnOpen, splitButtonMove, ddbEdit, ddbPrograms, ddbInfo })
        {
            ToolStripDropDownMenu menu = new()
            {
                ImageScalingSize = LogicalToDeviceUnits(new Size(16, 16)),
                Font = new Font(Font.FontFamily, 9f),
            };
            while (item.DropDownItems.Count > 0) { menu.Items.Add(item.DropDownItems[0]); } // bestehende Einträge (Bearbeiten-Menü) übernehmen
            item.DropDown = menu;
        }
        RestoreWindowBounds();
    }

    private async void MainForm_Shown(object sender, EventArgs e)
    {
        try { await viewHost.InitializeAsync(); }
        catch (WebView2RuntimeNotFoundException)
        {
            TaskDlg.MsgTaskDlg(Handle, Lng.T("Die WebView2-Runtime ist nicht installiert."), Lng.T("Bitte installiere sie über:") + Environment.NewLine + "https://developer.microsoft.com/microsoft-edge/webview2/", TaskDialogIcon.Error);
            Close();
            return;
        }
        catch (Exception ex) when (ex is DllNotFoundException or InvalidOperationException or System.Runtime.InteropServices.COMException or IOException or UnauthorizedAccessException)
        {
            // z.B. beschädigte Installation oder gesperrter Datenordner — sauberer Dialog statt WinForms-Absturzfenster
            TaskDlg.ErrTaskDlg(Handle, Lng.T("Die PDF-Anzeige (WebView2) konnte nicht gestartet werden."), ex);
            Close();
            return;
        }
        webView.KeyDown += WebView_KeyDown; // Tastenkürzel funktionieren auch, wenn der Viewer den Fokus hat
        viewHost.PdfFileDropped += (s, path) => LoadPdf(path, addToRecent: true); // Drop auf das Viewer-Areal
        InitDropDownClickShield();
        EnableClassicDragDrop();
        EnsureProgramList();
        RebuildProgramIconButtons();
        ApplyToolbarIcons();
        toolStrip.Resize += (s, args) => UpdateProgramIconVisibility();

        if (!string.IsNullOrEmpty(startFile) && File.Exists(startFile)) { LoadPdf(startFile, addToRecent: true); }
        else if (settings.ReopenLastFile && !string.IsNullOrEmpty(settings.LastFile) && File.Exists(settings.LastFile)) { LoadPdf(settings.LastFile); }
        else { UpdateUiState(); }
    }

    private void MainForm_FormClosing(object sender, FormClosingEventArgs e)
    {
        SetFullScreen(false); // sonst würden randlose Vollbild-Maße gespeichert
        settings.ReloadSharedLists(); // Listenänderungen anderer Instanzen nicht überschreiben
        settings.LastFile = currentFile?.FullName ?? string.Empty;
        var bounds = WindowState == FormWindowState.Normal ? Bounds : RestoreBounds;
        settings.WindowX = bounds.X;
        settings.WindowY = bounds.Y;
        settings.WindowWidth = bounds.Width;
        settings.WindowHeight = bounds.Height;
        settings.WindowMaximized = WindowState == FormWindowState.Maximized;
        settings.Save();
    }

    private void MainForm_Activated(object sender, EventArgs e)
    {
        if (currentFile == null) { return; }
        try
        {
            // Datei wurde extern geändert (z.B. in einem anderen Programm gespeichert) → Anzeige aktualisieren
            if (File.Exists(currentFile.FullName) && File.GetLastWriteTimeUtc(currentFile.FullName) != loadedWriteTimeUtc)
            {
                LoadPdf(currentFile.FullName);
            }
        }
        catch (IOException) { }
    }

    private void RestoreWindowBounds()
    {
        if (settings.WindowWidth > 200 && settings.WindowHeight > 200)
        {
            Rectangle bounds = new(settings.WindowX, settings.WindowY, settings.WindowWidth, settings.WindowHeight);
            if (Screen.AllScreens.Any(s => s.WorkingArea.IntersectsWith(bounds))) // nicht auf einem abgesteckten Monitor wiederherstellen
            {
                StartPosition = FormStartPosition.Manual;
                Bounds = bounds;
            }
        }
        if (settings.WindowMaximized) { WindowState = FormWindowState.Maximized; }
    }

    // ------------------------------------------------------------------ Menü-Schließen über dem WebView

    /// <summary>Praktisch unsichtbares Fenster über dem Viewer: Chromium läuft in einem eigenen Prozess,
    /// darum bekommt WinForms Klicks ins WebView nicht mit und offene Toolbar-Menüs blieben stehen.
    /// Solange ein Menü offen ist, fängt dieses Schild den ersten Klick ab und schließt das Menü
    /// (der Klick wird dabei wie bei Menüs üblich verschluckt).</summary>
    private sealed class ClickShieldForm : Form
    {
        public ClickShieldForm()
        {
            FormBorderStyle = FormBorderStyle.None;
            ShowInTaskbar = false;
            StartPosition = FormStartPosition.Manual;
            Opacity = 0.01; // bei 0 wären Klicks durchlässig
        }

        protected override bool ShowWithoutActivation => true; // darf dem Menü nicht den Fokus stehlen
    }

    private ClickShieldForm clickShield;
    private ToolStripDropDownItem[] dropDownButtons;

    private void InitDropDownClickShield()
    {
        clickShield = new ClickShieldForm();
        clickShield.MouseDown += (s, e) => CloseToolStripDropDowns();
        dropDownButtons = [btnOpen, splitButtonMove, ddbEdit, ddbPrograms, ddbInfo];
        foreach (var item in dropDownButtons)
        {
            item.DropDownOpened += (s, e) => ShowClickShield();
            item.DropDownClosed += (s, e) => clickShield.Hide();
        }
    }

    private void ShowClickShield()
    {
        clickShield.Bounds = new Rectangle(webView.PointToScreen(Point.Empty), webView.Size);
        clickShield.Show(this); // liegt über dem WebView, aber unter dem (Topmost-)Menü
    }

    private void CloseToolStripDropDowns()
    {
        foreach (var item in dropDownButtons) { item.HideDropDown(); }
        clickShield.Hide();
    }

    /// <summary>F11-Vollbild wie im Browser: randlos maximiert, Tool- und Statusleiste ausgeblendet; Esc oder F11 beendet.</summary>
    private void SetFullScreen(bool enable)
    {
        if (isFullScreen == enable) { return; }
        isFullScreen = enable;
        SuspendLayout();
        if (enable)
        {
            fullScreenPreviousState = WindowState;
            toolStrip.Visible = statusStrip.Visible = false;
            FormBorderStyle = FormBorderStyle.None;
            WindowState = FormWindowState.Normal;    // erzwingt die Neuberechnung, falls das Fenster bereits maximiert war
            WindowState = FormWindowState.Maximized; // randlos maximiert = echtes Vollbild inkl. Taskleiste
        }
        else
        {
            toolStrip.Visible = statusStrip.Visible = true;
            FormBorderStyle = FormBorderStyle.Sizable;
            WindowState = fullScreenPreviousState;
        }
        ResumeLayout();
    }

    // ------------------------------------------------------------------ Laden & Navigation

    private void LoadPdf(string path, int page = 0, bool addToRecent = false)
    {
        if (addToRecent) { previousFolder = null; } // bewusstes Öffnen beendet den Verschieben-Kontext fürs Blättern
        viewerDialogOpen = false; // das Neuladen des Dokuments schließt auch offene Viewer-Dialoge
        try { viewHost.Load(path, page); }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            TaskDlg.ErrTaskDlg(Handle, Lng.T("Die Datei konnte nicht geladen werden."), ex);
            return;
        }
        currentFile = new FileInfo(path);
        loadedWriteTimeUtc = currentFile.LastWriteTimeUtc;
        currentPageCount = PdfEditService.TryGetPageCount(path);
        if (addToRecent) // nur bei bewusstem Öffnen — nicht beim Blättern durch den Ordner
        {
            settings.ReloadSharedLists();
            settings.AddRecentFile(currentFile.FullName);
            settings.Save();
        }
        UpdateUiState();
    }

    private void UpdateUiState()
    {
        var hasFile = currentFile != null;
        Text = hasFile ? currentFile.Name + " – PDFlight" : "PDFlight";
        splitButtonMove.Enabled = btnCopy.Enabled = btnRename.Enabled = btnDelete.Enabled = btnShowInFolder.Enabled = ddbEdit.Enabled = btnPrint.Enabled = btnEmail.Enabled = hasFile;
        mnuSetPassword.Enabled = currentPageCount > 0;                // nur ohne bestehenden Kennwortschutz
        mnuRemovePassword.Enabled = hasFile && currentPageCount <= 0; // nur bei geschützter (oder unlesbarer) Datei
        foreach (var button in programIconButtons) { button.Enabled = hasFile; }
        if (hasFile)
        {
            var files = FileUtil.GetPdfFilesInFolder(currentFile.DirectoryName);
            var index = files.FindIndex(f => string.Equals(f, currentFile.FullName, StringComparison.OrdinalIgnoreCase));
            statusIndex.Text = Lng.T("Datei") + " " + (index >= 0 ? (index + 1).ToString() : "–") + "/" + files.Count;
            statusPath.Text = currentFile.FullName;
            var pages = currentPageCount > 0 ? currentPageCount + " " + (currentPageCount == 1 ? Lng.T("Seite") : Lng.T("Seiten")) + "   " : string.Empty;
            statusInfo.Text = $"{pages}{currentFile.Length / 1024.0:N0} KB   {currentFile.LastWriteTime:g}";
            btnPrev.Enabled = btnNext.Enabled = files.Count > 1;
        }
        else
        {
            statusIndex.Text = Lng.T("Datei") + " 0/0";
            statusPath.Text = Lng.T("Keine Datei geöffnet");
            statusInfo.Text = string.Empty;
            btnPrev.Enabled = btnNext.Enabled = false;
        }
    }

    private void OpenFile()
    {
        using OpenFileDialog dialog = new() { Filter = Lng.T("PDF-Dateien (*.pdf)|*.pdf"), Title = Lng.T("PDF-Datei öffnen") };
        if (currentFile != null) { dialog.InitialDirectory = currentFile.DirectoryName; }
        if (dialog.ShowDialog(this) == DialogResult.OK) { LoadPdf(dialog.FileName, addToRecent: true); }
    }

    /// <summary>Dropdown des Öffnen-Buttons: die zuletzt geöffneten Dateien.</summary>
    private void BtnOpen_DropDownOpening(object sender, EventArgs e)
    {
        settings.ReloadSharedLists();
        btnOpen.DropDownItems.Clear();
        foreach (var file in settings.RecentFiles)
        {
            ToolStripMenuItem item = new(Path.GetFileName(file).Replace("&", "&&"))
            {
                Tag = file,
                ToolTipText = file,
                Enabled = File.Exists(file),
                Image = ShellInfo.GetTypeIcon(".pdf", LogicalToDeviceUnits(16)),
            };
            item.Click += (s, args) => LoadPdf((string)((ToolStripMenuItem)s).Tag, addToRecent: true);
            btnOpen.DropDownItems.Add(item);
        }
        if (btnOpen.DropDownItems.Count == 0)
        {
            btnOpen.DropDownItems.Add(new ToolStripMenuItem(Lng.T("(keine zuletzt geöffneten Dateien)")) { Enabled = false });
        }
        else
        {
            btnOpen.DropDownItems.Add(new ToolStripSeparator());
            ToolStripMenuItem clear = new(Lng.T("Liste leeren")) { Image = MenuIcon(ToolbarIcons.Clear) };
            clear.Click += (s, args) => { settings.RecentFiles.Clear(); settings.Save(); };
            btnOpen.DropDownItems.Add(clear);
        }
    }

    /// <summary>Klassisches Drag &amp; Drop für Formular, Tool- und Statusleiste;
    /// Drops auf das Viewer-Areal fängt PdfViewHost über die file://-Navigation ab.</summary>
    private void EnableClassicDragDrop()
    {
        AllowDrop = true;
        DragEnter += HandleDragEnter;
        DragDrop += HandleDragDrop;
        toolStrip.AllowDrop = true;
        toolStrip.DragEnter += HandleDragEnter;
        toolStrip.DragDrop += HandleDragDrop;
        statusStrip.AllowDrop = true;
        statusStrip.DragEnter += HandleDragEnter;
        statusStrip.DragDrop += HandleDragDrop;
    }

    private void HandleDragEnter(object sender, DragEventArgs e)
    {
        e.Effect = GetDroppedPdf(e) != null ? DragDropEffects.Copy : DragDropEffects.None;
    }

    private void HandleDragDrop(object sender, DragEventArgs e)
    {
        var file = GetDroppedPdf(e);
        if (file != null)
        {
            LoadPdf(file);
            Activate();
        }
    }

    private static string GetDroppedPdf(DragEventArgs e)
    {
        if (e.Data?.GetDataPresent(DataFormats.FileDrop) == true && e.Data.GetData(DataFormats.FileDrop) is string[] files)
        {
            return files.FirstOrDefault(f => f.EndsWith(".pdf", StringComparison.OrdinalIgnoreCase) && File.Exists(f));
        }
        return null;
    }

    /// <summary>Blättert zur nächsten/vorherigen PDF-Datei im Ordner (mit Umlauf, wie in PDFMover).</summary>
    private string previousFolder; // Quellordner des letzten Verschiebens — fürs Blättern (Dialog wie in PDFMover)

    private void StepFile(int step)
    {
        if (currentFile == null) { return; }
        var folder = currentFile.DirectoryName;
        // Nach einem Verschieben: im Zielordner weiterblättern oder zurück in den bisherigen Ordner? (wie in PDFMover)
        if (previousFolder != null && Directory.Exists(previousFolder) && !string.Equals(previousFolder, folder, StringComparison.OrdinalIgnoreCase))
        {
            TaskDialogButton btnPrevious = new TaskDialogCommandLinkButton(Lng.T("Vorheriger Ordner:"), previousFolder);
            TaskDialogButton btnCurrent = new TaskDialogCommandLinkButton(Lng.T("Aktueller Ordner:"), folder);
            TaskDialogPage page = new()
            {
                Caption = Application.ProductName,
                Heading = string.Format(Lng.T("Du möchtest die {0} Datei öffnen."), step > 0 ? Lng.T("nächste") : Lng.T("vorherige")) + Environment.NewLine + Lng.T("Welcher Ordner soll durchsucht werden?"),
                AllowCancel = true,
                SizeToContent = true,
                Buttons = { btnPrevious, btnCurrent },
                DefaultButton = btnPrevious,
                Footnote = Lng.T("Wenn du abbrichst, wird der aktuelle Ordner verwendet.")
            };
            var result = TaskDialog.ShowDialog(Handle, page);
            if (result == btnPrevious)
            {
                var target = previousFolder;
                previousFolder = null;
                StepFileInFolder(target, step);
                return;
            }
            if (result == btnCurrent) { previousFolder = null; } // bei Abbruch bleibt die Frage fürs nächste Blättern bestehen
        }
        StepFileInFolder(folder, step);
    }

    /// <summary>Blättert im angegebenen Ordner; liegt die aktuelle Datei dort nicht (mehr),
    /// wird sie virtuell einsortiert, damit das Blättern an ihrer alten Position ansetzt.</summary>
    private void StepFileInFolder(string folder, int step)
    {
        var files = FileUtil.GetPdfFilesInFolder(folder);
        var reference = Path.Combine(folder, currentFile.Name);
        var index = files.FindIndex(f => string.Equals(f, reference, StringComparison.OrdinalIgnoreCase));
        if (index < 0)
        {
            if (files.Count == 0)
            {
                TaskDlg.MsgTaskDlg(Handle, Lng.T("Der Ordner enthält keine PDF-Dateien."), folder, TaskDialogIcon.Information);
                return;
            }
            files.Add(reference);
            FileUtil.SortNatural(files);
            index = files.FindIndex(f => string.Equals(f, reference, StringComparison.OrdinalIgnoreCase));
        }
        var next = (index + step + files.Count) % files.Count;
        if (next != index && !string.Equals(files[next], currentFile.FullName, StringComparison.OrdinalIgnoreCase)) { LoadPdf(files[next]); }
    }

    /// <summary>Nach Verschieben/Löschen: nächste Datei an gleicher Position laden oder Anzeige leeren.</summary>
    private void LoadNextAfterRemoval(List<string> files, int removedIndex)
    {
        if (removedIndex >= 0) { files.RemoveAt(removedIndex); } else { removedIndex = 0; }
        if (files.Count == 0)
        {
            currentFile = null;
            viewHost.CloseDocument();
            UpdateUiState();
            statusPath.Text = Lng.T("Der Ordner enthält keine weiteren PDF-Dateien.");
        }
        else { LoadPdf(files[removedIndex % files.Count]); }
    }

    // ------------------------------------------------------------------ Verschieben / Kopieren

    private void MoveCopyDialog(bool copy)
    {
        if (currentFile == null) { return; }
        Cursor.Current = Cursors.WaitCursor;
        settings.ReloadSharedLists(); // Ziel-/Zuletzt-Listen anderer Instanzen übernehmen
        var startFolder = settings.TargetFolders.FirstOrDefault(f => !string.IsNullOrEmpty(f) && Directory.Exists(f)) ?? string.Empty;
        var jumpToLastUsed = settings.JumpToLastUsed && settings.RecentFolders.Count > 0
            && Directory.Exists(settings.RecentFolders[0]) // sonst meldet der Dialog bei jedem Öffnen einen fehlenden Pfad
            && !string.Equals(startFolder, settings.RecentFolders[0], StringComparison.OrdinalIgnoreCase);

        using FolderSelectForm dialog = new(startFolder, copy, jumpToLastUsed);
        if (settings.RecentFolders.Count > 0) { dialog.RecentComboBox.Items.AddRange([.. settings.RecentFolders]); }
        dialog.TargetComboBox.Items.AddRange([.. settings.TargetFolders.Where(f => !string.IsNullOrEmpty(f))]);
        dialog.ShellTreePath = startFolder;

        if (dialog.ShowDialog(this) == DialogResult.OK)
        {
            var folder = dialog.ShellTreePath;
            if (string.IsNullOrEmpty(folder)) { return; }
            if (dialog.Add2Folderlist.Checked && !settings.TargetFolders.Any(f => string.Equals(f, folder, StringComparison.OrdinalIgnoreCase)))
            {
                settings.TargetFolders.Insert(0, folder);
                settings.Save();
            }
            MoveOrCopyTo(folder, copy);
        }
        Cursor.Current = Cursors.Default;
    }

    private void MoveOrCopyTo(string folder, bool copy)
    {
        if (currentFile == null) { return; }
        if (!Directory.Exists(folder))
        {
            TaskDlg.MsgTaskDlg(Handle, Lng.T("Der Zielordner existiert nicht."), folder, TaskDialogIcon.Warning);
            return;
        }
        if (string.Equals(Path.TrimEndingDirectorySeparator(folder), currentFile.DirectoryName, StringComparison.OrdinalIgnoreCase))
        {
            TaskDlg.MsgTaskDlg(Handle, Lng.T("Die Datei befindet sich bereits in diesem Ordner."), null, TaskDialogIcon.Information);
            return;
        }
        var destination = Path.Combine(folder, currentFile.Name);
        if (File.Exists(destination))
        {
            destination = AskReplaceOrRename(destination); // Ersetzen / name_n anlegen / Abbrechen (wie in PDFMover)
            if (destination == null) { return; }
        }
        try
        {
            settings.ReloadSharedLists(); // parallel laufende Instanzen nicht überschreiben
            if (copy)
            {
                File.Copy(currentFile.FullName, destination, true);
                statusPath.Text = Lng.T("Kopiert nach:") + " " + destination;
                AskWhichFileToShow(destination);
            }
            else
            {
                var sourceFolder = currentFile.DirectoryName;
                File.Move(currentFile.FullName, destination, true);
                LoadPdf(destination); // die verschobene Datei bleibt angezeigt — nun vom neuen Ort (wie in PDFMover)
                CheckForDuplicate(new FileInfo(destination));
                previousFolder = sourceFolder; // beim nächsten Blättern die Rückkehr in den bisherigen Ordner anbieten
            }
            settings.AddRecentFolder(folder);
            settings.Save();
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            TaskDlg.ErrTaskDlg(Handle, copy ? Lng.T("Kopieren fehlgeschlagen.") : Lng.T("Verschieben fehlgeschlagen."), ex);
        }
    }

    /// <summary>Zieldatei existiert bereits: Ersetzen, unter freiem name_n-Namen anlegen oder abbrechen (Dialog wie in PDFMover).
    /// Liefert den zu verwendenden Zielpfad oder null bei Abbruch.</summary>
    private string AskReplaceOrRename(string destination)
    {
        FileInfo destInfo = new(destination);
        var suggestion = FileUtil.SuggestAdditionalFileName(destInfo);
        TaskDialogButton btnReplace = new TaskDialogCommandLinkButton(Lng.T("&Ersetzen"),
            Lng.T("Die vorhandene Datei ersetzen") + $"\n{Lng.T("in")} {destInfo.DirectoryName}: {destInfo.Length / 1024} KB, {destInfo.LastWriteTime:d}");
        TaskDialogButton btnRename = new TaskDialogCommandLinkButton(Lng.T("&Umbenennen"), Lng.T("Eine neue Datei erstellen:") + "\n" + suggestion?.Name);
        var page = new TaskDialogPage()
        {
            Caption = currentFile.DirectoryName,
            Heading = Lng.T("Im Ziel ist bereits eine Datei mit diesem Namen vorhanden."),
            Text = destInfo.Name,
            AllowCancel = true,
            SizeToContent = true,
            Buttons = { btnReplace, TaskDialogButton.Cancel },
            DefaultButton = btnReplace
        };
        if (suggestion != null) { page.Buttons.Insert(1, btnRename); }
        var result = TaskDialog.ShowDialog(Handle, page);
        if (result == btnReplace) { return destination; }
        if (result == btnRename) { return suggestion.FullName; }
        return null;
    }

    /// <summary>Nach dem Kopieren: Dateikopie oder Originaldatei weiter anzeigen? (Dialog wie in PDFMover)</summary>
    private void AskWhichFileToShow(string copiedFile)
    {
        TaskDialogButton btnCopy = new TaskDialogCommandLinkButton(Lng.T("Dateikopie:"), copiedFile);
        TaskDialogButton btnSource = new TaskDialogCommandLinkButton(Lng.T("Originaldatei:"), currentFile.FullName);
        var page = new TaskDialogPage()
        {
            Caption = Application.ProductName,
            Heading = Lng.T("Welche Datei soll geöffnet werden?"),
            AllowCancel = true,
            SizeToContent = true,
            Buttons = { btnCopy, btnSource, TaskDialogButton.Cancel },
            DefaultButton = btnCopy
        };
        var result = TaskDialog.ShowDialog(Handle, page);
        if (result == btnCopy) { LoadPdf(copiedFile, addToRecent: true); }
        else if (result == btnSource) { settings.AddRecentFile(copiedFile); } // Kopie in die Zuletzt-Liste; das Original bleibt angezeigt
    }

    /// <summary>Nach dem Verschieben: liegt im Zielordner bereits eine inhaltsgleiche Datei? (wie in PDFMover;
    /// statt einer neuen Instanz wird die vorhandene Datei im selben Fenster angezeigt)</summary>
    private void CheckForDuplicate(FileInfo movedFile)
    {
        var duplicate = FileUtil.FindDuplicateInFolder(movedFile, movedFile.DirectoryName);
        if (duplicate == null) { return; }
        TaskDialogButton btnOpenExisting = new TaskDialogCommandLinkButton(Lng.T("Vorhandene Datei öffnen"), duplicate.Name);
        TaskDialogButton btnDeleteCurrent = new TaskDialogCommandLinkButton(Lng.T("Aktuelle Datei löschen"), movedFile.Name);
        var page = new TaskDialogPage()
        {
            Icon = TaskDialogIcon.Warning,
            Caption = movedFile.DirectoryName,
            Heading = Lng.T("Folgende Datei scheint identisch zu sein."),
            Text = $"{duplicate.Name} ({duplicate.Length / 1024} KB, {duplicate.LastWriteTime:d})",
            AllowCancel = true,
            SizeToContent = true,
            Buttons = { btnOpenExisting, btnDeleteCurrent, TaskDialogButton.Ignore },
            DefaultButton = btnOpenExisting
        };
        var result = TaskDialog.ShowDialog(Handle, page);
        if (result == btnOpenExisting) { LoadPdf(duplicate.FullName); }
        else if (result == btnDeleteCurrent)
        {
            try
            {
                FileSystem.DeleteFile(movedFile.FullName, UIOption.OnlyErrorDialogs, RecycleOption.SendToRecycleBin);
                LoadPdf(duplicate.FullName); // das Duplikat bleibt übrig und wird angezeigt
            }
            catch (OperationCanceledException) { }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException) { TaskDlg.ErrTaskDlg(Handle, Lng.T("Löschen fehlgeschlagen."), ex); }
        }
    }

    private void SplitButtonMove_ButtonClick(object sender, EventArgs e)
    {
        // Strg+Klick: direkt in den ersten Zielordner verschieben (wie in PDFMover)
        if ((ModifierKeys & Keys.Control) == Keys.Control && settings.TargetFolders.Count > 0 && Directory.Exists(settings.TargetFolders[0]))
        {
            MoveOrCopyTo(settings.TargetFolders[0], copy: false);
        }
        else { MoveCopyDialog(copy: false); }
    }

    private void SplitButtonMove_DropDownOpening(object sender, EventArgs e)
    {
        settings.ReloadSharedLists(); // Zielliste anderer Instanzen übernehmen
        splitButtonMove.DropDownItems.Clear();
        var targets = settings.TargetFolders.Where(f => !string.IsNullOrEmpty(f)); // Reihenfolge = Zielliste (sortierbar in den Einstellungen)
        foreach (var folder in targets)
        {
            ToolStripMenuItem item = new(folder.Replace("&", "&&")) { Enabled = Directory.Exists(folder), Tag = folder, Image = ShellInfo.GetTypeIcon(null, LogicalToDeviceUnits(16)) };
            item.Click += (s, args) => MoveOrCopyTo((string)((ToolStripMenuItem)s).Tag, copy: false);
            splitButtonMove.DropDownItems.Add(item);
        }
        if (splitButtonMove.DropDownItems.Count == 0)
        {
            splitButtonMove.DropDownItems.Add(new ToolStripMenuItem(Lng.T("(Zielliste ist leer)")) { Enabled = false });
        }
        splitButtonMove.DropDownItems.Add(new ToolStripSeparator());
        ToolStripMenuItem editList = new(Lng.T("Zielliste bearbeiten …")) { Image = MenuIcon(ToolbarIcons.Edit) };
        editList.Click += (s, args) => OpenSettings(SettingsForm.TabTargets);
        splitButtonMove.DropDownItems.Add(editList);
    }

    private void OpenSettings(int tabIndex)
    {
        settings.ReloadSharedLists();
        using SettingsForm dialog = new(settings, tabIndex);
        if (dialog.ShowDialog(this) == DialogResult.OK)
        {
            settings.TargetFolders = dialog.TargetFolders;
            settings.ExternalPrograms = dialog.ExternalPrograms;
            settings.JumpToLastUsed = dialog.JumpToLastUsed;
            settings.ConfirmDelete = dialog.ConfirmDelete;
            settings.ShowProgramIcons = dialog.ShowProgramIcons;
            settings.ShowToolbarIcons = dialog.ShowToolbarIcons;
            settings.LargeToolbarIcons = dialog.LargeToolbarIcons;
            settings.CloseOnEscape = dialog.CloseOnEscape;
            settings.ReopenLastFile = dialog.ReopenLastFile;
            var languageChanged = dialog.Language != settings.Language;
            settings.Language = dialog.Language;
            if (dialog.ClearRecentRequested) { settings.RecentFolders.Clear(); }
            settings.Save();
            if (languageChanged && TaskDlg.ConfirmTaskDlg(Handle, Lng.T("Die Sprachänderung wird nach einem Neustart des Programms wirksam."), Lng.T("Jetzt neu starten?")))
            {
                Application.Restart(); // löst FormClosing aus, die Einstellungen sind also gespeichert
            }
            RebuildProgramIconButtons();
            ApplyToolbarIcons();
        }
    }

    /// <summary>Versieht die Toolbar-Buttons mit Symbolen aus der Windows-Symbolschrift (abschaltbar in den Einstellungen).</summary>
    private void ApplyToolbarIcons()
    {
        var edge = LogicalToDeviceUnits(settings.LargeToolbarIcons ? 24 : 16); // DPI-gerecht; gilt auch für die Programm-Icons
        toolStrip.ImageScalingSize = new Size(edge, edge);
        var fontSize = settings.LargeToolbarIcons ? 10f : 9f; // größere Symbole → größere Schrift in der Symbolleiste
        if (Math.Abs(toolStrip.Font.Size - fontSize) > 0.1f) { toolStrip.Font = new Font(toolStrip.Font.FontFamily, fontSize); } // ToolStrip erbt die Form-Schrift nicht → direkt setzen
        var showIcons = settings.ShowToolbarIcons && ToolbarIcons.FontAvailable;
        var size = toolStrip.ImageScalingSize;
        void Set(ToolStripItem item, char glyph, bool imageOnly = false)
        {
            item.Image = showIcons ? ToolbarIcons.Get(glyph, size) : null;
            item.DisplayStyle = showIcons
                ? (imageOnly ? ToolStripItemDisplayStyle.Image : ToolStripItemDisplayStyle.ImageAndText)
                : ToolStripItemDisplayStyle.Text;
        }
        Set(btnOpen, ToolbarIcons.OpenFile);
        Set(btnPrev, ToolbarIcons.Previous, imageOnly: true);
        Set(btnNext, ToolbarIcons.Next, imageOnly: true);
        Set(splitButtonMove, ToolbarIcons.MoveToFolder);
        Set(btnCopy, ToolbarIcons.Copy);
        Set(btnRename, ToolbarIcons.Rename);
        Set(btnDelete, ToolbarIcons.Delete);
        Set(btnPrint, ToolbarIcons.Print);
        Set(btnEmail, ToolbarIcons.Mail);
        Set(ddbEdit, ToolbarIcons.Edit);
        Set(ddbPrograms, ToolbarIcons.AllApps);
        Set(btnShowInFolder, ToolbarIcons.FolderOpen);
        Set(btnSettings, ToolbarIcons.Settings);
        Set(ddbInfo, ToolbarIcons.Help, imageOnly: true);
        mnuDeletePages.Image = MenuIcon(ToolbarIcons.Delete); // Bearbeiten-Menü (Menüsymbole bleiben 16 px)
        mnuRotatePages.Image = MenuIcon(ToolbarIcons.Rotate);
        mnuAppendPdf.Image = MenuIcon(ToolbarIcons.Attach);
        mnuDuplex.Image = MenuIcon(ToolbarIcons.Interleave);
        mnuExtractPages.Image = MenuIcon(ToolbarIcons.Page);
        mnuUndo.Image = MenuIcon(ToolbarIcons.Undo);
        mnuSetPassword.Image = MenuIcon(ToolbarIcons.Lock);
        mnuRemovePassword.Image = MenuIcon(ToolbarIcons.Unlock);
        mnuProperties.Image = MenuIcon(ToolbarIcons.Info);
        mnuShortcuts.Image = MenuIcon(ToolbarIcons.Keyboard); // Info-Menü
        mnuCheckUpdate.Image = MenuIcon(ToolbarIcons.UpdateSearch);
        mnuAbout.Image = MenuIcon(ToolbarIcons.Info);
        UpdateProgramIconVisibility(); // die Buttonbreiten haben sich geändert
    }

    /// <summary>16-px-Symbol für Menüeinträge (die Menüs sind auf diese Größe festgelegt);
    /// null, wenn Symbole abgeschaltet sind.</summary>
    private Image MenuIcon(char glyph)
    {
        return settings.ShowToolbarIcons && ToolbarIcons.FontAvailable
            ? ToolbarIcons.Get(glyph, LogicalToDeviceUnits(new Size(16, 16)))
            : null;
    }

    // ------------------------------------------------------------------ Umbenennen / Löschen / Explorer

    private void RenameCurrent()
    {
        if (currentFile == null) { return; }
        using RenameForm dialog = new(currentFile);
        if (dialog.ShowDialog(this) != DialogResult.OK) { return; }
        var newPath = Path.Combine(dialog.NewFolder, dialog.NewName);
        if (string.Equals(newPath, currentFile.FullName, StringComparison.OrdinalIgnoreCase)) { UpdateUiState(); return; }
        try
        {
            File.Move(currentFile.FullName, newPath);
            if (!string.Equals(dialog.NewFolder, currentFile.DirectoryName, StringComparison.OrdinalIgnoreCase))
            {
                settings.AddRecentFolder(dialog.NewFolder); // Umbenennen mit Ordnerwechsel zählt wie ein Verschieben
                settings.Save();
            }
            LoadPdf(newPath); // aktualisiert Titel, Statusleiste und den im Viewer angezeigten Dateinamen
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            TaskDlg.ErrTaskDlg(Handle, Lng.T("Umbenennen fehlgeschlagen."), ex);
        }
    }

    private void DeleteCurrent()
    {
        if (currentFile == null) { return; }
        if (settings.ConfirmDelete)
        {
            var alwaysAsk = true;
            if (!TaskDlg.ConfirmTaskDlg(Handle, Lng.T("In den Papierkorb verschieben?"), currentFile.Name, Lng.T("Immer fragen"), ref alwaysAsk)) { return; }
            if (!alwaysAsk)
            {
                settings.ConfirmDelete = false; // wieder aktivierbar im Einstellungsdialog ("Vor dem Verschieben in den Papierkorb nachfragen")
                settings.ReloadSharedLists();
                settings.Save();
            }
        }
        var files = FileUtil.GetPdfFilesInFolder(currentFile.DirectoryName);
        var index = files.FindIndex(f => string.Equals(f, currentFile.FullName, StringComparison.OrdinalIgnoreCase));
        try { FileSystem.DeleteFile(currentFile.FullName, UIOption.OnlyErrorDialogs, RecycleOption.SendToRecycleBin); }
        catch (OperationCanceledException) { return; } // im Systemdialog abgebrochen
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            TaskDlg.ErrTaskDlg(Handle, Lng.T("Löschen fehlgeschlagen."), ex);
            return;
        }
        LoadNextAfterRemoval(files, index);
    }

    private void ShowInFolder()
    {
        if (currentFile == null) { return; }
        ShellUtil.ShowInFileManager(currentFile.FullName);
    }

    private bool emailInProgress;

    /// <summary>Erstellt eine neue E-Mail mit der aktuellen Datei als Anhang.
    /// Primär über das Shell-SendMail-DropTarget (respektiert die .mapimail-Zuordnung, z.B. eM Client);
    /// schlägt das fehl, als Fallback über Simple MAPI auf einem Hintergrund-Thread.</summary>
    private async void EmailCurrent()
    {
        if (currentFile == null || emailInProgress) { return; }
        emailInProgress = true;
        var path = currentFile.FullName;
        var subject = Path.GetFileNameWithoutExtension(currentFile.Name);
        try
        {
            try
            {
                MailSender.SendViaDropTarget(path); // muss auf dem UI-Thread (STA) laufen
            }
            catch (Exception ex) when (MailSender.IsComFailure(ex))
            {
                statusPath.Text = Lng.T("E-Mail wird erstellt (MAPI) …");
                var error = await Task.Run(() => MapiMailer.SendWithAttachment(path, subject));
                if (error != null)
                {
                    TaskDlg.MsgTaskDlg(Handle, Lng.T("Die E-Mail konnte nicht erstellt werden."), error, TaskDialogIcon.Warning);
                }
            }
        }
        finally
        {
            emailInProgress = false;
            if (currentFile != null) { statusPath.Text = currentFile.FullName; }
        }
    }

    // ------------------------------------------------------------------ Seitenoperationen (PDFsharp)

    /// <summary>Verschlüsselt die aktuelle Datei mit AES-256 (PDF 2.0) und einem
    /// Benutzer-Kennwort (Abfrage mit Wiederholungsfeld, mit Undo-Sicherung).</summary>
    private void SetPasswordDialog()
    {
        if (currentFile == null) { return; }
        if (!PdfEditService.CanOpen(currentFile.FullName, null))
        {
            TaskDlg.MsgTaskDlg(Handle, Lng.T("Die Datei ist bereits verschlüsselt."),
                Lng.T("Ein Kennwortschutz lässt sich über Bearbeiten → \"Kennwort entfernen\" aufheben."), TaskDialogIcon.Information);
            return;
        }
        using PasswordForm dialog = new(currentFile.Name, confirm: true);
        if (dialog.ShowDialog(this) != DialogResult.OK) { return; }
        var password = dialog.Password;
        if (RunPdfEdit(() => PdfEditService.SetPassword(currentFile.FullName, password), Lng.T("Vergeben des Kennworts")))
        {
            LoadPdf(currentFile.FullName); // der Viewer fragt nun selbst nach dem Kennwort
            statusPath.Text = Lng.T("Die Datei ist jetzt mit AES-256 verschlüsselt.");
        }
    }

    /// <summary>Entfernt den Kennwortschutz der aktuellen Datei (fragt das Kennwort ab, mit Undo-Sicherung).</summary>
    private void RemovePasswordDialog()
    {
        if (currentFile == null) { return; }
        if (PdfEditService.CanOpen(currentFile.FullName, null))
        {
            TaskDlg.MsgTaskDlg(Handle, Lng.T("Die Datei ist nicht verschlüsselt."), null, TaskDialogIcon.Information);
            return;
        }
        while (true)
        {
            using PasswordForm dialog = new(currentFile.Name);
            if (dialog.ShowDialog(this) != DialogResult.OK) { return; }
            var password = dialog.Password;
            if (!PdfEditService.CanOpen(currentFile.FullName, password))
            {
                TaskDlg.MsgTaskDlg(Handle, Lng.T("Das Kennwort ist falsch."), null, TaskDialogIcon.Warning);
                continue; // erneut fragen
            }
            if (RunPdfEdit(() => PdfEditService.RemovePassword(currentFile.FullName, password), Lng.T("Entfernen des Kennworts")))
            {
                LoadPdf(currentFile.FullName); // jetzt sind auch Seitenzahl und Bearbeitung verfügbar
                statusPath.Text = Lng.T("Das Kennwort wurde entfernt.");
            }
            return;
        }
    }

    /// <summary>Rückseiten-Scan einfügen (Duplex-Zusammenführung): Rückseiten aus einer zweiten Datei
    /// hinter die Seiten der aktuellen verzahnen — für Scanner ohne Duplex-Einheit.</summary>
    private void MergeDuplexDialog()
    {
        if (currentFile == null) { return; }
        if (currentPageCount <= 0) { ShowNotEditableMessage(); return; }
        TaskDialogPage intro = new() // erklärt den Zweck, bevor der Dateidialog erscheint
        {
            Caption = Application.ProductName,
            Heading = Lng.T("Rückseiten-Scan einfügen"),
            Text = Lng.T("Duplex.Intro",
                "Für Scanner ohne Duplex-Einheit: Die angezeigte Datei enthält die Vorderseiten (1, 3, 5 …)." + Environment.NewLine +
                "Wähle im nächsten Schritt die Datei mit den Rückseiten – sie wird mit den Vorderseiten" + Environment.NewLine +
                "zu einem vollständigen Dokument verzahnt (1, 2, 3 …)." + Environment.NewLine + Environment.NewLine +
                "Beide Dateien müssen gleich viele Seiten haben."),
            Icon = TaskDialogIcon.Information,
            AllowCancel = true,
            SizeToContent = true,
            Buttons = { TaskDialogButton.OK, TaskDialogButton.Cancel }
        };
        if (TaskDialog.ShowDialog(Handle, intro) != TaskDialogButton.OK) { return; }
        using OpenFileDialog dialog = new() { Filter = Lng.T("PDF-Dateien (*.pdf)|*.pdf"), Title = Lng.T("Datei mit den Rückseiten wählen"), InitialDirectory = currentFile.DirectoryName };
        if (dialog.ShowDialog(this) != DialogResult.OK) { return; }
        if (string.Equals(dialog.FileName, currentFile.FullName, StringComparison.OrdinalIgnoreCase))
        {
            TaskDlg.MsgTaskDlg(Handle, Lng.T("Bitte wähle eine andere Datei als die angezeigte."), null, TaskDialogIcon.Warning);
            return;
        }
        var backCount = PdfEditService.TryGetPageCount(dialog.FileName);
        if (backCount != currentPageCount)
        {
            TaskDlg.MsgTaskDlg(Handle, Lng.T("Die Seitenzahlen passen nicht zusammen."),
                string.Format(Lng.T("Vorderseiten: {0}, Rückseiten: {1}"), currentPageCount, backCount < 0 ? "?" : backCount), TaskDialogIcon.Warning);
            return;
        }
        TaskDialogButton btnReversed = new TaskDialogCommandLinkButton(Lng.T("In umgekehrter Reihenfolge"),
            Lng.T("Der Stapel wurde zum Scannen gewendet – letzte Rückseite zuerst (Standard)."));
        TaskDialogButton btnSame = new TaskDialogCommandLinkButton(Lng.T("In gleicher Reihenfolge"),
            Lng.T("Die Rückseiten wurden von vorn nach hinten gescannt."));
        TaskDialogPage page = new()
        {
            Caption = Application.ProductName,
            Heading = Lng.T("In welcher Reihenfolge liegen die Rückseiten vor?"),
            AllowCancel = true,
            SizeToContent = true,
            Buttons = { btnReversed, btnSame, TaskDialogButton.Cancel },
            DefaultButton = btnReversed
        };
        var result = TaskDialog.ShowDialog(Handle, page);
        if (result != btnReversed && result != btnSame) { return; }
        var backFile = dialog.FileName;
        if (RunPdfEdit(() => PdfEditService.MergeDuplex(currentFile.FullName, backFile, result == btnReversed), Lng.T("Einfügen der Rückseiten")))
        {
            LoadPdf(currentFile.FullName);
            statusPath.Text = string.Format(Lng.T("Die Rückseiten aus \"{0}\" wurden eingefügt."), Path.GetFileName(backFile));
        }
    }

    /// <summary>Führt eine Dokumentänderung mit vorheriger Undo-Sicherung aus; false bei Fehler.</summary>
    private bool RunPdfEdit(Action edit, string actionName)
    {
        Cursor.Current = Cursors.WaitCursor;
        try
        {
            BackupForUndo();
            edit();
            return true;
        }
        catch (Exception ex) when (PdfEditService.IsPdfReadError(ex))
        {
            TaskDlg.ErrTaskDlg(Handle, string.Format(Lng.T("{0} fehlgeschlagen."), actionName), ex);
            return false;
        }
        finally { Cursor.Current = Cursors.Default; }
    }

    private void ShowNotEditableMessage()
    {
        TaskDlg.MsgTaskDlg(Handle, Lng.T("Die Datei kann nicht bearbeitet werden."),
            Lng.T("Möglicherweise ist sie verschlüsselt oder beschädigt.") + Environment.NewLine
            + Lng.T("Ein Kennwortschutz lässt sich über Bearbeiten → \"Kennwort entfernen\" aufheben."), TaskDialogIcon.Warning);
    }

    private void DeletePagesDialog()
    {
        if (currentFile == null) { return; }
        if (currentPageCount <= 0) { ShowNotEditableMessage(); return; }
        if (currentPageCount == 1)
        {
            TaskDlg.MsgTaskDlg(Handle, Lng.T("Die Datei hat nur eine Seite."), Lng.T("Zum Löschen der ganzen Datei benutze den Papierkorb (Strg+Umschalt+Entf)."), TaskDialogIcon.Information);
            return;
        }
        var currentPage = ClampedCurrentPage();
        using PageRangeForm dialog = new(Lng.T("Seiten löschen"), currentPageCount, emptyMeansAll: false, showRotation: false,
            defaultRange: currentPage > 0 ? currentPage.ToString() : null); // meist soll die gerade angezeigte Seite gelöscht werden
        if (dialog.ShowDialog(this) != DialogResult.OK) { return; }
        var pages = dialog.SelectedPages;
        if (pages.Count >= currentPageCount)
        {
            TaskDlg.MsgTaskDlg(Handle, Lng.T("Mindestens eine Seite muss erhalten bleiben."), null, TaskDialogIcon.Warning);
            return;
        }
        var remaining = currentPageCount - pages.Count;
        if (RunPdfEdit(() => PdfEditService.DeletePages(currentFile.FullName, pages), Lng.T("Seiten löschen")))
        {
            LoadPdf(currentFile.FullName, Math.Min(pages[0], remaining));
            statusPath.Text = pages.Count == 1 ? string.Format(Lng.T("Seite {0} wurde gelöscht."), pages[0]) : string.Format(Lng.T("{0} Seiten wurden gelöscht."), pages.Count);
        }
    }

    /// <summary>Aktuelle Seite des Viewers, auf die bekannte Seitenzahl begrenzt; 0 = unbekannt.</summary>
    private int ClampedCurrentPage()
    {
        var page = viewHost.TryGetCurrentPage();
        return page >= 1 && page <= currentPageCount ? page : 0;
    }

    private void RotatePagesDialog()
    {
        if (currentFile == null) { return; }
        if (currentPageCount <= 0) { ShowNotEditableMessage(); return; }
        using PageRangeForm dialog = new(Lng.T("Seiten drehen"), currentPageCount, emptyMeansAll: true, showRotation: true,
            infoText: Lng.T("Drehen.Info",
                "Die Drehung wird dauerhaft in der Datei gespeichert." + Environment.NewLine +
                "Die Drehen-Schaltfläche des Viewers ändert dagegen nur die Ansicht."));
        if (dialog.ShowDialog(this) != DialogResult.OK) { return; }
        var pages = dialog.SelectedPages;
        if (RunPdfEdit(() => PdfEditService.RotatePages(currentFile.FullName, pages, dialog.RotationDelta), Lng.T("Seiten drehen")))
        {
            LoadPdf(currentFile.FullName, pages.Count == currentPageCount ? 0 : pages[0]);
            statusPath.Text = pages.Count == currentPageCount ? Lng.T("Alle Seiten wurden gedreht.")
                : (pages.Count == 1 ? string.Format(Lng.T("Seite {0} wurde gedreht."), pages[0]) : string.Format(Lng.T("{0} Seiten wurden gedreht."), pages.Count));
        }
    }

    private void AppendPdfDialog()
    {
        if (currentFile == null) { return; }
        if (currentPageCount <= 0) { ShowNotEditableMessage(); return; }
        using OpenFileDialog dialog = new() { Filter = Lng.T("PDF-Dateien (*.pdf)|*.pdf"), Title = Lng.T("PDF-Datei anhängen"), InitialDirectory = currentFile.DirectoryName };
        if (dialog.ShowDialog(this) != DialogResult.OK) { return; }
        if (string.Equals(dialog.FileName, currentFile.FullName, StringComparison.OrdinalIgnoreCase))
        {
            TaskDlg.MsgTaskDlg(Handle, Lng.T("Die Datei kann nicht an sich selbst angehängt werden."), null, TaskDialogIcon.Warning);
            return;
        }
        var firstNewPage = currentPageCount + 1;
        if (RunPdfEdit(() => PdfEditService.AppendPdf(currentFile.FullName, dialog.FileName), Lng.T("Anhängen")))
        {
            LoadPdf(currentFile.FullName, firstNewPage);
            statusPath.Text = string.Format(Lng.T("\"{0}\" wurde angehängt."), Path.GetFileName(dialog.FileName));
        }
    }

    private void ExtractPagesDialog()
    {
        if (currentFile == null) { return; }
        if (currentPageCount <= 0) { ShowNotEditableMessage(); return; }
        var currentPage = ClampedCurrentPage();
        using PageRangeForm rangeDialog = new(Lng.T("Seiten extrahieren"), currentPageCount, emptyMeansAll: false, showRotation: false,
            defaultRange: currentPage switch // Vorschlag: aktuelle bis letzte Seite
            {
                0 => null,
                _ when currentPage == currentPageCount => currentPage.ToString(),
                _ => $"{currentPage}-{currentPageCount}",
            });
        if (rangeDialog.ShowDialog(this) != DialogResult.OK) { return; }
        using SaveFileDialog saveDialog = new()
        {
            Filter = Lng.T("PDF-Dateien (*.pdf)|*.pdf"),
            Title = Lng.T("Auszug speichern"),
            InitialDirectory = currentFile.DirectoryName,
            FileName = string.Format(Lng.T("{0} – Auszug.pdf"), Path.GetFileNameWithoutExtension(currentFile.Name)),
        };
        if (saveDialog.ShowDialog(this) != DialogResult.OK) { return; }
        if (string.Equals(saveDialog.FileName, currentFile.FullName, StringComparison.OrdinalIgnoreCase))
        {
            TaskDlg.MsgTaskDlg(Handle, Lng.T("Der Auszug kann die geöffnete Datei nicht überschreiben."), null, TaskDialogIcon.Warning);
            return;
        }
        try
        {
            Cursor.Current = Cursors.WaitCursor;
            PdfEditService.ExtractPages(currentFile.FullName, saveDialog.FileName, rangeDialog.SelectedPages);
            statusPath.Text = Lng.T("Auszug gespeichert:") + " " + saveDialog.FileName;
        }
        catch (Exception ex) when (PdfEditService.IsPdfReadError(ex))
        {
            TaskDlg.ErrTaskDlg(Handle, Lng.T("Extrahieren fehlgeschlagen."), ex);
        }
        finally { Cursor.Current = Cursors.Default; }
    }

    private void ShowProperties()
    {
        if (currentFile == null) { return; }
        PdfInfo info;
        try { info = PdfEditService.ReadInfo(currentFile.FullName); }
        catch (Exception ex) when (PdfEditService.IsPdfReadError(ex)) { ShowNotEditableMessage(); return; }
        currentFile.Refresh();
        using PropertiesForm dialog = new(info, currentFile);
        if (dialog.ShowDialog(this) == DialogResult.OK && dialog.InfoChanged)
        {
            if (RunPdfEdit(() => PdfEditService.WriteInfo(currentFile.FullName, dialog.DocTitle, dialog.DocAuthor, dialog.DocSubject, dialog.DocKeywords), Lng.T("Speichern der Eigenschaften")))
            {
                LoadPdf(currentFile.FullName);
                statusPath.Text = Lng.T("Die Dokumenteigenschaften wurden gespeichert.");
            }
        }
    }

    private void BackupForUndo()
    {
        var folder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "PDFlight");
        Directory.CreateDirectory(folder);
        undoBackupFile = Path.Combine(folder, "undo.pdf");
        File.Copy(currentFile.FullName, undoBackupFile, true);
        undoTargetFile = currentFile.FullName;
        mnuUndo.Enabled = true;
    }

    private void UndoLastChange()
    {
        if (undoTargetFile == null || !File.Exists(undoBackupFile)) { return; }
        try { File.Copy(undoBackupFile, undoTargetFile, true); }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            TaskDlg.ErrTaskDlg(Handle, Lng.T("Rückgängig fehlgeschlagen."), ex);
            return;
        }
        var file = undoTargetFile;
        undoTargetFile = null;
        mnuUndo.Enabled = false;
        LoadPdf(file);
        statusPath.Text = Lng.T("Die letzte Änderung wurde rückgängig gemacht.");
    }

    // ------------------------------------------------------------------ Externe Programme

    private void EnsureProgramList()
    {
        settings.ExternalPrograms.RemoveAll(p => string.IsNullOrEmpty(p) || !File.Exists(p));
        if (settings.ExternalPrograms.Count == 0)
        {
            settings.ExternalPrograms = ProgramFinder.DetectPrograms();
            settings.Save();
        }
    }

    private void DdbPrograms_DropDownOpening(object sender, EventArgs e)
    {
        settings.ReloadSharedLists();
        ddbPrograms.DropDownItems.Clear();
        var number = 1;
        foreach (var exe in settings.ExternalPrograms.Take(ProgramFinder.MaxPrograms))
        {
            ToolStripMenuItem item = new(ProgramFinder.GetDisplayName(exe))
            {
                Tag = exe,
                Image = GetProgramIcon(exe),
                ShortcutKeyDisplayString = Lng.T("Strg+") + number,
                ToolTipText = exe,
                Enabled = currentFile != null,
            };
            item.Click += (s, args) => LaunchExternalProgram((string)((ToolStripMenuItem)s).Tag);
            ddbPrograms.DropDownItems.Add(item);
            number++;
        }
        if (ddbPrograms.DropDownItems.Count == 0)
        {
            ddbPrograms.DropDownItems.Add(new ToolStripMenuItem(Lng.T("(keine Programme gefunden)")) { Enabled = false });
        }
        ddbPrograms.DropDownItems.Add(new ToolStripSeparator());
        ToolStripMenuItem openWith = new(Lng.T("Öffnen mit …")) { Enabled = currentFile != null, Image = MenuIcon(ToolbarIcons.OpenWith) };
        openWith.Click += (s, args) => OpenWithDialog();
        ddbPrograms.DropDownItems.Add(openWith);
        ddbPrograms.DropDownItems.Add(new ToolStripSeparator());
        ToolStripMenuItem managePrograms = new(Lng.T("Programme verwalten …")) { Image = MenuIcon(ToolbarIcons.Settings) };
        managePrograms.Click += (s, args) => OpenSettings(SettingsForm.TabPrograms);
        ddbPrograms.DropDownItems.Add(managePrograms);
    }

    private void LaunchExternalProgram(string exePath)
    {
        if (currentFile == null || !File.Exists(exePath)) { return; }
        try { Process.Start(new ProcessStartInfo(exePath, $"\"{currentFile.FullName}\"") { UseShellExecute = false }); }
        catch (Exception ex) when (ex is System.ComponentModel.Win32Exception or InvalidOperationException or FileNotFoundException)
        {
            TaskDlg.ErrTaskDlg(Handle, Lng.T("Das Programm konnte nicht gestartet werden."), ex);
        }
    }

    private void LaunchProgramByIndex(int index)
    {
        if (index < settings.ExternalPrograms.Count) { LaunchExternalProgram(settings.ExternalPrograms[index]); }
    }

    private readonly List<ToolStripButton> programIconButtons = [];

    /// <summary>Zeigt die Symbole der externen Programme zusätzlich als Toolbar-Buttons.
    /// Dank Overflow=Never verschwinden sie automatisch, wenn die Fensterbreite nicht reicht.</summary>
    private void RebuildProgramIconButtons()
    {
        foreach (var button in programIconButtons)
        {
            toolStrip.Items.Remove(button);
            button.Dispose();
        }
        programIconButtons.Clear();
        if (!settings.ShowProgramIcons) { return; }

        var insertIndex = toolStrip.Items.IndexOf(toolStripSeparator5); // direkt hinter dem Programme-Menü
        var number = 1;
        foreach (var exe in settings.ExternalPrograms.Take(ProgramFinder.MaxPrograms))
        {
            var icon = GetProgramIconGray(exe); // grau, damit sie sich den MDL2-Symbolen unterordnen; im Menü bleiben sie farbig
            if (icon != null)
            {
                ToolStripButton button = new()
                {
                    DisplayStyle = ToolStripItemDisplayStyle.Image,
                    Image = icon,
                    Overflow = ToolStripItemOverflow.Never, // bei schmalem Fenster ausblenden statt ins Überlaufmenü
                    Tag = exe,
                    ToolTipText = ProgramFinder.GetDisplayName(exe) + " (" + Lng.T("Strg+") + number + ")",
                    Enabled = currentFile != null,
                };
                button.Click += (s, e) => LaunchExternalProgram((string)((ToolStripItem)s).Tag);
                toolStrip.Items.Insert(insertIndex++, button);
                programIconButtons.Add(button);
            }
            number++;
        }
        UpdateProgramIconVisibility();
    }

    /// <summary>Blendet die Programm-Icons aus, sobald sie nicht mehr neben alle übrigen Buttons passen —
    /// die Kernfunktionen haben Vorrang und sollen nicht ins Überlaufmenü rutschen.</summary>
    private void UpdateProgramIconVisibility()
    {
        if (programIconButtons.Count == 0) { return; }
        var requiredWidth = 0;
        foreach (ToolStripItem item in toolStrip.Items)
        {
            if (item is not ToolStripButton button || !programIconButtons.Contains(button))
            {
                requiredWidth += item.GetPreferredSize(Size.Empty).Width + item.Margin.Horizontal; // unabhängig von der aktuellen Sichtbarkeit
            }
        }
        var iconsWidth = programIconButtons.Sum(b => b.GetPreferredSize(Size.Empty).Width + b.Margin.Horizontal);
        var fits = requiredWidth + iconsWidth + 8 <= toolStrip.DisplayRectangle.Width;
        foreach (var button in programIconButtons) { button.Visible = fits; }
    }

    private void OpenWithDialog()
    {
        if (currentFile == null) { return; }
        // Windows-Dialog "Öffnen mit" (Pfad hier bewusst ohne Anführungszeichen — OpenAs_RunDLL erwartet das so)
        Process.Start(new ProcessStartInfo("rundll32.exe", "shell32.dll,OpenAs_RunDLL " + currentFile.FullName) { UseShellExecute = false });
    }

    private Image GetProgramIcon(string exePath)
    {
        if (!programIcons.TryGetValue(exePath, out var image))
        {
            try
            {
                using var icon = Icon.ExtractAssociatedIcon(exePath);
                image = icon?.ToBitmap();
            }
            catch (Exception ex) when (ex is ArgumentException or IOException) { image = null; }
            programIcons[exePath] = image;
        }
        return image;
    }

    private readonly Dictionary<string, Image> programIconsGray = new(StringComparer.OrdinalIgnoreCase);

    private Image GetProgramIconGray(string exePath)
    {
        if (!programIconsGray.TryGetValue(exePath, out var image))
        {
            image = ToolbarIcons.ToGrayscale(GetProgramIcon(exePath));
            programIconsGray[exePath] = image;
        }
        return image;
    }

    // ------------------------------------------------------------------ Tastenkürzel

    private bool HandleShortcut(Keys keyData)
    {
        switch (keyData)
        {
            case Keys.O | Keys.Control: OpenFile(); return true;
            case Keys.F4:
            case Keys.M | Keys.Control: MoveCopyDialog(copy: false); return true;
            case Keys.K | Keys.Control: MoveCopyDialog(copy: true); return true;
            case Keys.F2:
            case Keys.U | Keys.Control: RenameCurrent(); return true;
            // erst nach der Rückkehr aus dem Chromium-Tastatur-Callback: solange der läuft, wartet Chromium
            // auf unsere Antwort und kann die UIA-Seitenabfrage nicht bedienen (sie liefe in den Timeout)
            case Keys.Delete | Keys.Control: BeginInvoke(DeletePagesDialog); return true;
            case Keys.X | Keys.Control: BeginInvoke(ExtractPagesDialog); return true; // eXtrahieren; nutzt ebenfalls die UIA-Seitenabfrage
            case Keys.Delete | Keys.Control | Keys.Shift when currentFile != null: DeleteCurrent(); return true;
            case Keys.R | Keys.Control: RotatePagesDialog(); return true;
            // Ansicht drehen (das Viewer-Kürzel Strg+] ist auf deutschen Tastaturen unerreichbar);
            // BeginInvoke: die UIA-Abfrage nicht im Chromium-Tastatur-Callback starten (s. Strg+Entf)
            case Keys.R | Keys.Control | Keys.Shift: BeginInvoke(() => viewHost.RotateView(clockwise: true)); return true;
            case Keys.L | Keys.Control | Keys.Shift: BeginInvoke(() => viewHost.RotateView(clockwise: false)); return true;
            case Keys.G | Keys.Control: BeginInvoke(viewHost.FocusPageField); return true;              // Gehe zu Seite (Zahl + Enter)
            case Keys.I | Keys.Control | Keys.Shift: BeginInvoke(viewHost.ToggleContents); return true; // Inhalte-Leiste
            case Keys.B | Keys.Control | Keys.Shift: BeginInvoke(viewHost.FitToWidth); return true;     // Breite (Viewer-Kürzel Strg+\ ist auf deutschen Tastaturen unerreichbar)
            case Keys.Space | Keys.Control: BeginInvoke(viewHost.ToggleLayout); return true;            // ein-/zweiseitiges Layout
            case Keys.Z | Keys.Control when undoTargetFile != null: UndoLastChange(); return true;
            case Keys.I | Keys.Control: ShowProperties(); return true;
            case Keys.Oemcomma | Keys.Control: OpenSettings(SettingsForm.TabGeneral); return true; // Strg+, wie in vielen Editoren
            case Keys.Enter | Keys.Alt when currentFile != null: ShellUtil.ShowFileProperties(currentFile.FullName); return true; // Windows-Dateieigenschaften, wie im Explorer
            case Keys.K | Keys.Control | Keys.Shift when currentFile != null: CopyPathToClipboard(); return true; // Strg+Umschalt+C wäre Explorer-üblich, ist aber vom AutoHotkey-Skript des Autors belegt
            case Keys.E | Keys.Control: EmailCurrent(); return true;
            case Keys.Right | Keys.Control | Keys.Shift: StepFile(1); return true;   // Strg+Pfeile ohne Umschalt gehören dem Viewer (Zoom & Co.)
            case Keys.Left | Keys.Control | Keys.Shift: StepFile(-1); return true;
            case Keys.F1: TaskDlg.ShowShortcutsPdf(Handle, Icon); return true;
            case Keys.F11: SetFullScreen(!isFullScreen); return true;
            case Keys.Escape | Keys.Shift when settings.CloseOnEscape: Close(); return true; // Shift+Esc beendet sofort (wie in NetRadio)
            case Keys.Escape when isFullScreen: SetFullScreen(false); return true;
            case Keys.Escape when settings.CloseOnEscape: return HandleEscapeToClose();
        }
        if ((keyData & (Keys.Control | Keys.Alt | Keys.Shift)) == Keys.Control)
        {
            var key = keyData & Keys.KeyCode;
            if (key is >= Keys.D1 and <= Keys.D9) { LaunchProgramByIndex(key - Keys.D1); return true; } // Strg+1 … Strg+9: externe Programme
        }
        return false;
    }

    /// <summary>Kopiert den vollständigen Pfad der angezeigten Datei in die Zwischenablage (Strg+Umschalt+C, wie im Explorer).</summary>
    private void CopyPathToClipboard()
    {
        try
        {
            Clipboard.SetText(currentFile.FullName);
            statusPath.Text = Lng.T("Der Dateipfad wurde in die Zwischenablage kopiert.");
        }
        catch (System.Runtime.InteropServices.ExternalException ex) // Zwischenablage von anderem Programm gesperrt
        {
            TaskDlg.ErrTaskDlg(Handle, Lng.T("Kopieren in die Zwischenablage fehlgeschlagen."), ex);
        }
    }

    private DateTime lastEscape = DateTime.MinValue;

    /// <summary>Beenden erst beim zweiten Esc kurz hintereinander: Das erste Esc wird nicht verschluckt und
    /// schließt so einen eventuell offenen Viewer-Dialog (Suchleiste, Seitenansicht, Drucken) — deren Zustand
    /// ist über die WebView2-API nicht abfragbar. Shift+Esc beendet sofort (s. HandleShortcut).</summary>
    private bool HandleEscapeToClose()
    {
        var now = DateTime.UtcNow;
        if ((now - lastEscape).TotalMilliseconds <= 1500) { Close(); return true; }
        lastEscape = now;
        return false; // das erste Esc geht an den Viewer
    }

    protected override bool ProcessCmdKey(ref Message msg, Keys keyData)
    {
        return HandleShortcut(keyData) || base.ProcessCmdKey(ref msg, keyData);
    }

    // Der Zustand der Viewer-Dialoge (Suchleiste, Seitenansicht, Drucken …) ist über die WebView2-API nicht
    // abfragbar. Wird aber SICHER einer geöffnet — per Tastatur, die läuft hier durch —, setzt das nächste Esc
    // das Beenden/Vollbild-Verlassen aus und geht stattdessen an Chromium, das den Dialog schließt.
    // Per Maus geöffnete Viewer-Dialoge (Toolbar-Buttons) bleiben unsichtbar; dort beendet Esc wie gewohnt.
    private bool viewerDialogOpen;

    private void WebView_KeyDown(object sender, KeyEventArgs e)
    {
        if (e.KeyData is (Keys.Control | Keys.F) or Keys.F3 or (Keys.Control | Keys.P)) { viewerDialogOpen = true; return; } // Suche bzw. Drucken — an Chromium durchreichen
        if (e.KeyData == Keys.Escape && viewerDialogOpen) { viewerDialogOpen = false; return; }
        if (HandleShortcut(e.KeyData)) { e.Handled = true; }
    }

    // ------------------------------------------------------------------ Toolbar-Klicks

    private void BtnOpen_Click(object sender, EventArgs e)
    {
        OpenFile();
    }
    private void BtnPrev_Click(object sender, EventArgs e)
    {
        StepFile(-1);
    }
    private void BtnNext_Click(object sender, EventArgs e)
    {
        StepFile(1);
    }
    private void BtnCopy_Click(object sender, EventArgs e)
    {
        MoveCopyDialog(copy: true);
    }
    private void BtnRename_Click(object sender, EventArgs e)
    {
        RenameCurrent();
    }
    private void BtnDelete_Click(object sender, EventArgs e)
    {
        DeleteCurrent();
    }
    private void BtnShowInFolder_Click(object sender, EventArgs e)
    {
        ShowInFolder();
    }
    private void BtnSettings_Click(object sender, EventArgs e)
    {
        OpenSettings(SettingsForm.TabGeneral);
    }
    private void MnuShortcuts_Click(object sender, EventArgs e)
    {
        TaskDlg.ShowShortcutsPdf(Handle, Icon);
    }
    private async void MnuCheckUpdate_Click(object sender, EventArgs e)
    {
        await TaskDlg.UpdateTaskDlg(Handle);
    }
    private void MnuAbout_Click(object sender, EventArgs e)
    {
        TaskDlg.AboutTaskDlg(Handle, Icon);
    }
    private void BtnPrint_Click(object sender, EventArgs e)
    {
        viewHost.ShowPrintDialog();
    }
    private void BtnEmail_Click(object sender, EventArgs e)
    {
        EmailCurrent();
    }
    private void MnuDeletePages_Click(object sender, EventArgs e)
    {
        DeletePagesDialog();
    }
    private void MnuRotatePages_Click(object sender, EventArgs e)
    {
        RotatePagesDialog();
    }
    private void MnuAppendPdf_Click(object sender, EventArgs e)
    {
        AppendPdfDialog();
    }
    private void MnuExtractPages_Click(object sender, EventArgs e)
    {
        ExtractPagesDialog();
    }
    private void MnuDuplex_Click(object sender, EventArgs e)
    {
        MergeDuplexDialog();
    }
    private void MnuSetPassword_Click(object sender, EventArgs e)
    {
        SetPasswordDialog();
    }
    private void MnuRemovePassword_Click(object sender, EventArgs e)
    {
        RemovePasswordDialog();
    }
    private void MnuUndo_Click(object sender, EventArgs e)
    {
        UndoLastChange();
    }
    private void MnuProperties_Click(object sender, EventArgs e)
    {
        ShowProperties();
    }
}
